### ISSUE TITLE
RFC #0300 - Tracking for RFC Process Update

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#1]
## [RFC #0300](https://github.com/emberjs/rfcs/pull/0300) - Tracking for RFC Process Update

Champion: @kategengler 	
---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Ember.js Team:

No work needed.

### Ember CLI Team:

- [x] Move ember-cli/rfcs merged RFCs into emberjs/rfcs
- [x] Close all outstanding issues and PRs on ember-cli-rfcs 
- [x] Archive ember-cli/rfcs

### Learning Team:

N/A

### Steering Committee:

- [x] Update emberjs/rfcs README to reflect the RFC
- [x] Update emberjs/rfcs templates to reflect the RFC
- [ ] Create a way to track merged RFCs
- [ ] Ensure teams adopt updated RFC process & review & plan RFCs

### Other tasks:

- [ ] Backfill Champions for on-going RFCs (assign to RFC PR)
- [ ] Backfill Header format to older RFCs

## Open Questions

- Should the champion also be specified in the header of the RFC template?
