### ISSUE TITLE
RFC #0395 - Tracking for @ember-data packages

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#11]
## [RFC #0395](https://github.com/emberjs/rfcs/pull/0395) - Tracking for @ember-data packages

Champion: @runspired

---

### Ember Data Team:

- [x] convert to monorepo
   🔒 @heroiceric https://github.com/emberjs/data/pull/5919
- [x] publish new packages
   🔒 @runspired as part of 3.10 -beta
- [x] update blueprints to use new packages
   🔒 @runspired https://github.com/emberjs/data/pull/6045
- [x] mappings for use by codemods and lint rules
  🔒 @dycriller https://github.com/ember-data/ember-data-rfc395-data
- [x] provide codemod for converting from `DS.` to new structure
  🔒 @dcyriller
- [x] provide codemod for converting from `ember-data/` to new structure
  🔒 @dycriller
- [x] introduce a lint rule deprecating use of `DS.` and `ember-data/` imports
  🔒 @dycriller
- [x] provide mechanism to test "canary" builds
- [x] eliminate usage of `DS.` namespace in yuidoc comments in favor of correct package names/imports

### Learning Team:

- [x] update docs and guides to reflect new import locations (guides-source have 60 results in 9 files of `import DS from 'ember-data'`) https://github.com/ember-learn/guides-source/issues/740
- [x] check API docs data generation to see if they are created correctly. Is anything getting dropped? https://github.com/emberjs/data/issues/6016 and #740
- [x] fix any issues from ^^^^ https://github.com/emberjs/data/issues/6016
- [x] Optional - write a test to check the ember-data docs, in the same way as is done in ember.js repo  https://github.com/emberjs/data/issues/6017 
- [ ] update the "mental models" presented in the Ember Data guides content 
 https://github.com/ember-learn/guides-source/issues/741

### Ember CLI Team

N/A

**Comment by runspired** [comment]
I've introduced a label for tracking issues and PRs related to this effort in `ember-data` here: https://github.com/emberjs/data/labels/TRACK-packages

**Comment by runspired** [comment]
Note that we missed the `3.10` release target for this in part due to the continued need to validate/update documentation and documentation generation. We will need to make this a key focus for the `3.11` cycle to ensure we can release packages then.

cc @jenweber for some insight on how we can help on this.

**Comment by kategengler** [comment]
@runspired If you can serialize the tracking here too, that'd be great. The checklist enables seeing progress of the RFC.

**Comment by jenweber** [comment]
@runspired I think maybe what we should do is pair the docs generation testing. It's helpful to have some people on the data team who are familiar with it, in order to help speed up future refactors too and protect against dropping things. Can you ask the team if anyone would like to pair it with me or maybe @sivakumar-kailasam, if he's available? We can get this locked down for 3.11. I don't expect any major issues.

If you want to give it a try solo, the linked issue has the instructions (emberjs/data#6016). I think they are fairly complete, though I have never done the API docs app viewing for ember data before, only ember.js.

**Comment by jamescdavis** [comment]
Guides update started in https://github.com/ember-learn/guides-source/pull/814
