### ISSUE TITLE
RFC #0272 - Tracking for Deprecate Function.prototype.on, Function.prototype.property, Function.prototype.observes

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#12]
## [RFC #0272](https://github.com/emberjs/rfcs/pull/0272) - Tracking for Deprecate Function.prototype.on, Function.prototype.property, Function.prototype.observes

Champions: @rwjblue, @locks 	 

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Ember.js Team:

- [x] Implement deprecation with svelte flags https://github.com/emberjs/ember.js/pull/17910

### Ember CLI Team:

- [ ] Write/review codemod to refactor (migrate from ember-watson?)

### Learning Team:

- [x] Write deprecation guide https://github.com/ember-learn/deprecation-app/pull/330
- [x] Review guides for deprecated usages.
- [ ] Review API documentation for deprecated usages.

### Steering Committee:

N/A

**Comment by rwjblue** [comment]
Deprecation guide PR: https://github.com/ember-learn/deprecation-app/pull/330

**Comment by rwjblue** [comment]
I did a review of the guides-source and didn't spot any function prototype extension usage, so I believe that item is 👍.

**Comment by rwjblue** [comment]
FYI - This is slated for release in 3.11
