### ISSUE TITLE
RFC #0369 - Tracking for Deprecate Computed Overridability and `.readOnly()`

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#18]
## [RFC #0369](https://github.com/emberjs/rfcs/pull/0369) - Tracking for Deprecate Computed Overridability and `.readOnly()`

Champion: @rwjblue 	

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Ember.js Team:

- [x] Implemented https://github.com/emberjs/ember.js/pull/17470
- [ ] Optional Feature to opt-out of overrideability
- [ ] Remove overrideability support (4.0)

### Ember CLI Team:

N/A

### Ember Data Team:

N/A

### Learning Team:

- [x] Deprecation guide entry https://github.com/ember-learn/deprecation-app/pull/254

### Steering Committee:

N/A

**Comment by rwjblue** [comment]
Released in 3.9.0 🎉
