### ISSUE TITLE
RFC #0332 - Tracking for Record Links & Meta

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#19]
## [RFC #0332](https://github.com/emberjs/rfcs/pull/0332) - Tracking for Record Links & Meta

Champion: @runspired

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Ember.js Team:

N/A

### Ember CLI Team:

N/A

### Learning Team:

- [ ] update the documentation to specify the differences between `links` and `meta` in json:api (potentially [here](https://guides.emberjs.com/release/models/handling-metadata/))
- [ ] make sure there is a section in the guides which specifies which types of store functions currently support meta & links (by the time this RFC is done I assume that they all would be supported?)
- [ ] consider adding a section to API docs for each function to say if they support meta or not 
- [ ] consider adding explicit documentation about the `potential name conflict and the default conflict resolution`
- [ ] update the Ember Data API docs with this feature
- [ ] Make sure you can see meta as an attribute in Inspector (if we expect this to work)
- [ ] Write a release blog post blurb

### Steering Committee:

N/A

**Comment by mansona** [comment]
@runspired can we get an indication of how much of this has been done? I have just experimented with using links in a `store.query()` and it works as expected 🤔

**Comment by runspired** [comment]
@mansona this RFC is for `record` links & meta, not queries. Queries have indeed worked for some while.

**Comment by sdhull** [comment]
In terms of actually getting this done in Ember Data, is it basically just adding `public meta?: Dict<any>;` and then assigning it in the constructor? I still don't really grok the internals of ember data 😬
