### ISSUE TITLE
RFC #0416 - Tracking for Glimmer Components

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#2]
## [RFC #0416](https://github.com/emberjs/rfcs/pull/0416) - Tracking for Glimmer Components

Champions: @tomdale, @rwjblue

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Ember.js Team:

Status: Currently released in alpha, requires updates for tracked properties, and Glimmer.js

- Feature Work
  - [x] Initial implementation (https://github.com/glimmerjs/glimmer.js/pull/168)
  - [ ] Update Glimmer.js to add element modifiers so we can sync the two APIs
  - [ ] Use proxy based `args`
- Bugfixes
  - [x] Freeze `args` in DEBUG (https://github.com/glimmerjs/glimmer.js/pull/178)
  - [x] Fix `args` tracking by using `set` (https://github.com/glimmerjs/glimmer.js/pull/180)
  - [x] Make component generic over args (https://github.com/glimmerjs/glimmer.js/pull/182)

### Ember CLI Team:

N/A

### Learning Team:
- [ ] Get Native Class components working in Ember Inspector https://github.com/emberjs/ember-inspector/issues/931
- [x] Write a conversion guide for classic to native  https://github.com/ember-learn/guides-source/pull/455
- [x] Write Guides sections teaching native class components as the only way https://github.com/ember-learn/guides-source/pull/455
- [x] Show native class components in the Quickstart https://github.com/ember-learn/guides-source/pull/455
- [ ] Show native classes in Ember API docs examples
- [ ] Revise the Components explanation in the API docs
- [ ] Convert Super Rentals app to Native Class components - WIP https://github.com/ember-learn/super-rentals/issues/118 and https://github.com/ember-learn/super-rentals/pull/123
- [ ] Write the prose for Super Rentals 
- [ ] Write content for the release blog post 

All of the Guides and Super Rentals work above will be merged at the point of the Octane release, since merges to master get deployed.

**Comment by locks** [comment]
I believe this RFC has been completed.
