### ISSUE TITLE
RFC #0331 - Tracking for Deprecate Globals Resolver

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#20]
## [RFC #0331](https://github.com/emberjs/rfcs/pull/0331) - Tracking for Deprecate Globals Resolver

Champion: @rwjblue 	

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Ember.js Team:

- [x] Deprecate instantiating `@ember/application/globals-resolver` (in `init` of `packages/@ember/application/globals-resolver.ts`)
- [x] Deprecate using `Ember.Resolver` / `Ember.DefaultResolver` (in `packages/ember/index.js`)

### Ember CLI Team:

- [x] Update ember-resolver to avoid extending from `Ember.Resolver` / `Ember.DefaultResolver` https://github.com/ember-cli/ember-resolver/pull/243

### Ember Data Team:

N/A

### Learning Team:
The RFC indicates that the guides already don't include this. No work needed.

**Comment by Gaurav0** [comment]
@rwjblue @MelSumner  Please update checkboxes.

**Comment by rwjblue** [comment]
OK, this is going to land in 3.16. Thank you @Gaurav0!
