### ISSUE TITLE
RFC #0329 - Tracking for Deprecate the use of Ember Evented in Ember Data

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#21]
## [RFC #0329](https://github.com/emberjs/rfcs/pull/0329) - Tracking for Deprecate the use of Ember Evented in Ember Data

Champion: @runspired

---

### Ember Data Team

- [x] replace `Evented` use with custom `DeprecatedEvented` 
- [x] custom deprecation for `didLoad` event on `AdapterPopulatedRecordArray`
- [x] custom deprecations for event methods on `@ember/model`
- [x] fix tests to not make use of these events

### Learning 

- [x] mark evented as deprecated
- [x] Write a deprecation guide entry https://github.com/ember-learn/deprecation-app

Evented is not used anywhere in the Guides.

**Comment by pete-the-pete** [comment]
@runspired you can assign this to me (if that makes sense). Also curious how the rfc-tracking issues map back to https://github.com/emberjs/data issues

**Comment by runspired** [comment]
@pete-the-pete the issue stays assigned to me as the "core team champion". Essentially this means I am responsible for ensuring that adequate code-reviews occur, work is spec'd out, and delegated. E.G. I am the on-call and accountable person for this even if I am not the individual responsible for the implementation.

The concept of RFC Tracking issues is a bit new and we are still getting used to the flow, however in terms of how it maps back to `emberjs/data` issues typically for each bullet item here there should be an issue or PR in ember-data (or in another place if docs/cli/ etc. are involved). This issue is for tracking all the tasks across the various repo's and to make it easy for the learning team and community to be able to follow along on the status of landing a merged RFC.

**Comment by pete-the-pete** [comment]
@runspired this what I have so far: https://github.com/pete-the-pete/data/commit/14e01d8fe3439731486b2bbed89b13ee56876037

I added a custom DeprecatedEvent mixin that gets use in place of Evented. If that's not the right path, let me know.

Other questions:
1. "Custom deprecation for didLoad event on AdapterPopulatedRecordArray" - is the deprecation to go on the didLoad in [_setInternalModels](https://github.com/emberjs/data/blob/master/packages/store/addon/-private/system/record-arrays/adapter-populated-record-array.js#L88)?
2. "custom deprecations for event methods on @ember/model" - the RFC mentions 
    > DS.Model will also receive deprecation warnings when a model is defined with the following methods: becameError, becameInvalid, didCreate, didDelete, didLoad, didUpdate, ready, rolledBack.

     We discussed it, but I want to make sure i remember correctly...would the deprecation warning be when those [methods are called](https://github.com/emberjs/data/blob/master/packages/store/addon/-private/system/model/model.js#L830-L844)?

3. Can you refresh my memory on how I can the noise by having checking some cached 'this has been called before' for the `testCondition` of the deprecate call?

4. Generally speaking, what should the language of the deprecation call look like? Should it try to tell the user where (which object) the call was made, or do we just rely on the stack trace?

5. kind of unrelated, but there's a lot of `You are using @belongsTo decorator from ember-decorators. This decorator is deprecated, you can now use Ember's built in decorators directly`, is that something we (I) could tackle?

**Comment by runspired** [comment]
Sync'd with Pete this morning and answered each of these questions.

**Comment by pete-the-pete** [comment]
@runspired can this be closed now?
