### ISSUE TITLE
RFC #0324 - Tracking for Deprecate Component#isVisible

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#22]
## [RFC #0324](https://github.com/emberjs/rfcs/blob/master/text/0324-deprecate-component-isvisible.md) - Tracking for Component#isVisible

Champion: @rwjblue 	

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

#### ember.js
- [ ] introduce deprecation (https://github.com/emberjs/ember.js/issues/17918)
- [ ] remove deprecation in `until` release

### Ember CLI Team:
N/A

### Ember Data Team:
N/A

#### ember.js
- [ ] check `deprecated` flag is displayed correctly in API Docs once deprecation is introduced
- [ ] check that `isVisible` API description from the API Docs is removed successfully once deprecation is outlived

#### deprecation-app
- [ ] [add a deprecation to the deprecations app](https://github.com/ember-learn/deprecation-app/issues/321)

#### guides-source
- [x] check guides-source for instances of `isVisible` and if applicable remove / replace the mentions in code examples with the alternative [mentioned in the RFC](https://github.com/Parrryy/rfcs/blob/5bd04ccbdb4be7c4b3aff2e56cbdd7a49d3fb7cf/text/0000-deprecate-component-isvisible.md#how-we-teach-this)

### Steering Committee:
N/A

**Comment by jayjayjpg** [comment]
Just had a quick look at the Guides and saw that there's no mention of `Component#isVisible` - we should be able to check this one off the list of learning items

**Comment by rwjblue** [comment]
@gavinjoyce has a PR up over in https://github.com/emberjs/ember.js/pull/17948

**Comment by sandstrom** [comment]
@kategengler I think we can close this issue, or at least mark some subpoints as completed:

- [x] introduce deprecation
- [x] add a deprecation to the deprecations app

This was worked on in: https://github.com/emberjs/ember.js/pull/17948
