### ISSUE TITLE
RFC #0318 - Tracking for `array` helper

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#23]
## [RFC #0318](https://github.com/emberjs/rfcs/pull/0318) - Tracking for `array` helper

Champion: @mmun 	

---

> All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

[Filled out based on [previous tracking issue](https://github.com/emberjs/ember.js/issues/17052)]

#### [ember.js](https://github.com/emberjs/ember.js)

- [x] https://github.com/emberjs/ember.js/pull/17054

### Ember CLI Team:

No work expected

### Ember Data Team:

No work expected 

#### [ember-learn/guides-source](https://github.com/ember-learn/guides-source)

- [x] https://github.com/ember-learn/guides-source/pull/209

### Steering Committee:

No work expected 

### Other considerations

- [x] Polyfill - Update https://github.com/kellyselden/ember-array-helper to be a "true" polyfill. https://github.com/kellyselden/ember-array-helper/issues/89

**Comment by rwjblue** [comment]
RE: polyfill, I think it would be pretty easy to make https://github.com/kellyselden/ember-array-helper into a "true" polyfill. What do you think @kellyselden?

**Comment by kellyselden** [comment]
Totally agree.

**Comment by rwjblue** [comment]
OK, I've created https://github.com/kellyselden/ember-array-helper/issues/89 and updated the description above.

**Comment by rwjblue** [comment]
While I think we should _totally_ do the polyfill, I'm going to close this (@kategengler said it was OK!!!!!) because all teams have signed off and the polyfill isn't mentioned in the original RFC anyways.

**Comment by kategengler** [comment]
Released in Ember.js v3.8.0
