### ISSUE TITLE
RFC #0287 - Tracking for Promote {{-in-element}} to public API 

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#25]
## [RFC #0287](https://github.com/emberjs/rfcs/pull/0287) - Tracking for Promote {{-in-element}} to public API 

Champion: @rwjblue

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

#### glimmer-vm
- [x] implement semantic change (https://github.com/glimmerjs/glimmer-vm/pull/918)

#### ember.js
- [x] upgrade glimmer-vm dependency
- [x] document API
- [x] release

### Ember CLI Team:
N/A

### Ember Data Team:
N/A

#### ember.js
- [x] Add documentation for new built-in helper `{{in-lement}}` to the API Docs: https://github.com/emberjs/ember.js/issues/17947

#### guides-source
- [ ] Add a section on the usage of `{{in-element}}` to the Guides, incl. at least one descriptive example: https://github.com/ember-learn/guides-source/issues/751

#### addon ecosystem
- [x] Reach out to maintainers of [ember-wormwhole](https://github.com/yapplabs/ember-wormhole) or [ember-elsewhere](https://github.com/ef4/ember-elsewhere) to point users to new framework-provided helper in their docs

### Steering Committee:
N/A

**Comment by simonihmig** [comment]
For the record: https://github.com/kaliber5/ember-in-element-polyfill has been updated to include the semantic change of the RFC as of v0.2.0, and should work as a polyfill going back to Ember 2.12!

**Comment by mansona** [comment]
I've done a bit of digging and it looks like the change was made to glimmer-vm in https://github.com/glimmerjs/glimmer-vm/pull/918/commits/22d1ea9180d50e23fb5d71aa0241ab5f129006fa which was then released in glimmer-vm@0.40.0 🤔

As the glimmer-vm was updated past v0.40.0 in https://github.com/emberjs/ember.js/commit/ade8188cc2c54fd6aade041354496100d57d3836 does that mean that the public `{{in-element}}` API is available from Ember v3.18?

**Comment by simonihmig** [comment]
@mansona my understanding is that though GlimmerVM has indeed been updated, and features all what is necessary to expose a public `in-element`, this has not been done yet on the side of Ember. See:
* https://github.com/emberjs/ember.js/pull/18727
* https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/transform-in-element.ts#L11-L44

Though I am also curious what is preventing us from doing the necessary updates on Ember's side to make `in-element` public? /cc @rwjblue @chancancode 

If it's "just" time to work on it, that I could try it...

**Comment by simonihmig** [comment]
A few points can be checked off here:
* GlimmerVM has ben update a while ago
* support in Ember has just been unlocked (https://github.com/emberjs/ember.js/pull/18867)
* API docs where a part of that

**Comment by locks** [comment]
It has been enabled in canary via https://github.com/emberjs/ember.js/pull/18927.

**Comment by sandstrom** [comment]
Regarding the "addon ecosystem" todo above I've submitted two PRs. Maybe that's enough to tick that box here? Still up to them to decide, but at least we've pinged them now.

- https://github.com/yapplabs/ember-wormhole/pull/122
- https://github.com/ef4/ember-elsewhere/pull/44
