### ISSUE TITLE
RFC #0236 - Tracking for Ember.String deprecation

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#26]
## [RFC #0236](https://github.com/emberjs/rfcs/blob/master/text/0236-deprecation-ember-string.md) - Tracking for Ember.String deprecation

Champion: @locks 	

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Misc
- investigate if we should build a codemod for moving people off of the `Ember.String` prototype extension

### Ember.js Team

- ember.js
  - [x] Deprecate `loc` entirely (should be replaced with e.g. ember-intl) ([PR](https://github.com/emberjs/ember.js/pull/19211))
  - [x] Deprecate `String.prototype` extensions ([PR](https://github.com/emberjs/ember.js/pull/19234))
  - [ ] Deprecate `Ember.String` namespace (deprecates importing from `@ember/string` without the addon installed) ([PR](https://github.com/emberjs/ember.js/pull/18904))
  - [x] [Deprecate importing `isHtmlSafe` and `htmlSafe` from `@ember/string`](https://github.com/emberjs/ember.js/pull/15626) (done via linting)
- [`@ember/string`](https://github.com/emberjs/ember-string)
  - [x] extract addon
  - [x] publish to npm
  - [x] deprecate `loc`
  - [ ] Don't include duplicated code (?)
  - [ ] publish 2.0 without `loc` ([PR](https://github.com/emberjs/ember-string/pull/28))

### Ember CLI Team

- [ember-cli-babel](https://github.com/babel/ember-cli-babel)
  - [x] [blacklist `@ember/string` if present](https://github.com/babel/ember-cli-babel/pull/176)
- [babel-plugin-ember-modules-api-polyfill](https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill)
  - [x] make it aware of `@ember/string`
- [ember-rfc176-data](https://github.com/ember-cli/ember-rfc176-data)
  - [x] [Move `htmlSafe` and `isHTMLSafe` to `@ember/template`](https://github.com/ember-cli/ember-rfc176-data/pull/38)

### Ember Data Team

- [ember-data](https://github.com/emberjs/data)
  - [x] add `@ember/string` as a dependency [[PR](https://github.com/emberjs/data/pull/5967)]
  - [ ] potentially remove usages of `@ember/string`?

### Learning Team

- [deprecation-app](https://github.com/ember-learn/deprecation-app/)
  - [x] add entry for `loc` deprecation ([PR](https://github.com/ember-learn/deprecation-app/pull/688))
  - [ ] add entry for prototype extension deprecation ([PR](https://github.com/ember-learn/deprecation-app/pull/696))
  - [ ] add entry for `Ember.String` deprecation (deprecates importing from `@ember/string` without the addon installed)

### Steering Committee

No work required.

**Comment by jamescdavis** [comment]
FYI: Effective as of Ember 3.25, importing `isHtmlSafe` and `htmlSafe` from `@ember/string` has now been formally deprecated in the code (https://github.com/emberjs/ember.js/pull/19339) and in the deprecation app (https://github.com/ember-learn/deprecation-app/pull/758).
