### ISSUE TITLE
RFC #0386 - Tracking for Remove jQuery by Default

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#3]
## [RFC #0386](https://github.com/emberjs/rfcs/pull/0386) - Remove jQuery by Default

Champion: @rwjblue

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

[Filled out from @simonihmig's [Quest issue](https://github.com/emberjs/ember.js/issues/17476)]

#### [ember.js](https://github.com/emberjs/ember.js)

- [x] add a (universal, non-silenceable) deprecation warning to `Ember.$()`
🔒@simonihmig, PR: https://github.com/emberjs/ember.js/pull/17489
- [x] add a deprecation warning to `this.$()` in an `Ember.Component`
🔒@simonihmig, PR: https://github.com/emberjs/ember.js/pull/17488
- [x] make sure user sees deprecation warning of jQuery integration itself, i.e. neither the `jquery-integration` optional feature flag is set to false nor `@ember/jquery` has been installed.
🔒@simonihmig, PR: https://github.com/ember-cli/ember-cli/pull/8399
- [x] wrap all jQuery related code for svelte
🔒@simonihmig, PR: https://github.com/emberjs/ember.js/pull/17525

#### Removal phase (4.0)

- [ ] remove deprecated functions
- [ ] remove the jQuery specific code paths in the EventDispatcher

#### [@ember/jquery](https://github.com/emberjs/ember-jquery)

- [x] Add support for `Component.$()`
🔒@simonihmig, WIP PR: https://github.com/emberjs/ember-jquery/pull/27
- [ ] Add jQuery-based EventDispatcher replacement 
🔒@simonihmig, WIP PR: https://github.com/emberjs/ember-jquery/pull/31
- [x] Make `import $ from 'jquery';` work
🔒@simonihmig, PR: https://github.com/emberjs/ember-jquery/pull/33

#### [@ember/test-helpers](https://github.com/emberjs/ember-test-helpers)

- [x] Add a deprecation warning to `this.$()` in component integration tests, based on `setupRenderingTest()`
🔒@simonihmig, PR: https://github.com/emberjs/ember-test-helpers/pull/543

#### [ember-cli](https://github.com/ember-cli/ember-cli)

- [x] Update app blueprint, stage 1: Update `@ember/jquery` to latest version
PR: https://github.com/ember-cli/ember-cli/pull/8396
- [x] Update app blueprint, stage 2: remove jQuery
🔒@cyriller, PR: https://github.com/ember-cli/ember-cli/pull/8394

#### [ember-cli-babel](https://github.com/babel/ember-cli-babel)

- [x] Do not transpile `import $ from 'jquery';` to `Ember.$` if the right version of `@ember/jquery` is present
🔒@simonihmig, PR: https://github.com/babel/ember-cli-babel/pull/261

#### [ember-data](https://github.com/emberjs/data)

- [x] Make ember-data work with ember-fetch
🔒@tchak PR: https://github.com/emberjs/data/pull/5386
- [x] reworked fetch support in ember-data (avoid dependency on ember-fetch) emberjs/data#6077.
- [x] ensure ember-data's CI tests without jQuery emberjs/data#5975

#### [ember-fetch](https://github.com/ember-cli/ember-fetch)

- [ ] Provide a replacement API for jQuery's `prefilter`

#### Website

- [x] Add a [deprecation guide](https://emberjs.github.io/rfcs/0386-remove-jquery.html#how-we-teach-this)
🔒@simonihmig PR: https://github.com/ember-learn/deprecation-app/pull/255
- [x] Prepare the Octane edition to teach that jQuery is not part of the default
- [x] Make sure that Super Rentals works without jQuery enabled
- [ ] Write a section for the Release Blog Post of Octane (when we change the blueprints)

#### guides-source
- [x] remove usages of `import $`, `this.$()`, and `$.ajax`

#### ember.js
- [x] review API documentation for usage of jQuery

#### ember-data
- [ ] review API documentation for usage of jQuery

### Steering Committee:
No work expected

**Comment by simonihmig** [comment]
The `ember-data` todo can be checked off, as per https://github.com/emberjs/data/pull/5900! :tada:

**Comment by rwjblue** [comment]
We reworked the fetch support in ember-data over in https://github.com/emberjs/data/pull/6077.

https://github.com/emberjs/data/pull/5975 is working to ensure ember-data's CI is running properly without jQuery.

**Comment by nlfurniss** [comment]
@simonihmig for `remove usages of import $, this.$(), and $.ajax`, this there a starting version of the docs we're targeting?

It doesn't make sense to remove jQuery mentions in v1.0.0 of the docs, but maybe starting from 3.0.0 it does?

**Comment by simonihmig** [comment]
> It doesn't make sense to remove jQuery mentions in v1.0.0 of the docs, but maybe starting from 3.0.0 it does?

AFAIK docs for past versions will not be updated in general, only for the latest `release`, right?

Not sure what's still left to do here? I found [these references](https://github.com/ember-cli/ember-cli/pull/8394) of jQuery usage, but they all seem to have been fixed already.

**Comment by nlfurniss** [comment]
> > It doesn't make sense to remove jQuery mentions in v1.0.0 of the docs, but maybe starting from 3.0.0 it does?
> 
> AFAIK docs for past versions will not be updated in general, only for the latest `release`, right?
> 
> Not sure what's still left to do here? I found [these references](https://github.com/ember-cli/ember-cli/pull/8394) of jQuery usage, but they all seem to have been fixed already.

In that case I think the docs item can be checked off :-)

**Comment by rwjblue** [comment]
Just merged the ember-cli update to drop jQuery for `ember new foo` (generally slated for ember-cli@3.13 at this point).

**Comment by simonihmig** [comment]
There are now two PRs open for the corresponding points listed under "Removal phase (4.0)":
* https://github.com/emberjs/ember.js/pull/19551
* https://github.com/emberjs/ember.js/pull/19552

**Comment by simonihmig** [comment]
The two item under "Removal phase (4.0)" can be checked off!

PRs:
* https://github.com/emberjs/ember.js/pull/19677
* https://github.com/emberjs/ember.js/pull/19676
* https://github.com/emberjs/ember.js/pull/19675
* https://github.com/emberjs/ember.js/pull/19666
* https://github.com/emberjs/ember.js/pull/19665
