### ISSUE TITLE
RFC #0418 - Tracking for Deprecate Route Render APIs

### ISSUE THREAD

**Issue by rwjblue** [emberjs/rfc-tracking#30]
## [RFC #0418](https://github.com/emberjs/rfcs/blob/master/text/0418-deprecate-route-render-methods.md) - Tracking for Deprecate Route Render APIs 

Champion: @chadhietala 

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Ember.js Team:
- [ ] implement deprecation
- [ ] remove deprecation

### Ember CLI Team:

N/A

### Ember Data Team:

N/A

#### ember.js
- [ ] review deprecated usages of API

#### guides-source
- [ ] review deprecated usages of API

#### deprecations-app
- [ ] write deprecation guide

### Steering Committee:

N/A

**Comment by abhishek97** [comment]
I would like to work on implementing the deprecation warning, any ideas how do i get started?
Any example PR on deprecating something similar i can look at?
