### ISSUE TITLE
RFC #0403- Tracking for [DATA] identifiers

### ISSUE THREAD

**Issue by runspired** [emberjs/rfc-tracking#31]
## [RFC #0403](https://github.com/emberjs/rfcs/blob/master/text/0403-ember-data-identifiers.md) - Tracking for [DATA] Identifiers

Champion: @runspired 

#### [ember-data](https://github.com/emberjs/data)

- [x] new API docs
- [x] tests around timing behaviors specified in the RFC
- [x] implementation of identifiers behind a feature flag
   🔒 @runspired https://github.com/emberjs/data/pull/5914
- [x] feature-flag removed, identifiers shipped
- [x] removal of non-identifier mechanisms for handling identity in internals

### Learning Team:

- [x] review new API docs

As Identifiers will be a largely internal concern except for power-users until RFCs improving other existing APIs to make use of Identifiers land, there is no additional need from the learning team at this time for the guides.

### Ember CLI Team

N/A
