### ISSUE TITLE
RFC #0471 - Tracking for {{on}} Modifier

### ISSUE THREAD

**Issue by rwjblue** [emberjs/rfc-tracking#32]
## [RFC #0471](https://github.com/emberjs/rfcs/blob/master/text/0471-on-modifier.md) - Tracking for {{on}} Modifier 

Champion: @rwjblue

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

#### [ember.js](https://github.com/emberjs/ember.js)
- [x] implement modifier https://github.com/emberjs/ember.js/pull/17960
- [x] publish polyfill https://github.com/buschtoens/ember-on-modifier
- [x] enable feature flag https://github.com/emberjs/ember.js/pull/18026

### Ember CLI Team:
N/A

### Ember Data Team:
N/A

#### ember.js
- [ ] API documentation

#### [guides-source](https://github.com/ember-learn/guides-source)
- [ ] document modifier usage patterns

### Steering Committee:
N/A

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/17960 adds initial implementation

**Comment by MelSumner** [comment]
@toddjordan do you know if this has been PR'd to the API docs yet?

**Comment by locks** [comment]
Work has been finalized on this RFC :)
