### ISSUE TITLE
RFC #0470 - Tracking for {{fn}} Helper

### ISSUE THREAD

**Issue by rwjblue** [emberjs/rfc-tracking#33]
## [RFC #0470](https://github.com/emberjs/rfcs/blob/master/text/0470-fn-helper.md) - Tracking for {{fn}} Helper 

Champion: @pzuraq 

---

#### [ember.js](https://github.com/emberjs/ember.js)
- [x] implement `fn` helper https://github.com/emberjs/ember.js/pull/17941
- [x] ensure `fn` helper can be nested https://github.com/emberjs/ember.js/pull/17961
- [x] enable by default https://github.com/emberjs/ember.js/pull/17965
- [x] write and publish polyfill

### Ember CLI Team:
N/A

### Ember Data Team:
N/A

#### API docs
- [x] document helper https://github.com/emberjs/ember.js/pull/17965

#### Octane Guides
- [x] document functionality in Component chapter https://github.com/ember-learn/guides-source/issues/828

#### Blog
- [x] write a blurb for the release post about this feature

### Steering Committee:
N/A

**Comment by rwjblue** [comment]
Initial implementation in https://github.com/emberjs/ember.js/pull/17941

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/17961 fixes a bug preventing `fn` from being nested

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/17965 adds api docs and enables the implementation by default

**Comment by rwjblue** [comment]
emberjs/ember.js#17965 landed and therefore `fn` is slated for release in 3.11 (barring any significant issues)...

**Comment by locks** [comment]
I believe there's nothing left to do for this RFC.
