### ISSUE TITLE
RFC #0425 - Tracking for Website Redesign

### ISSUE THREAD

**Issue by rwjblue** [emberjs/rfc-tracking#35]
## [RFC #0425](https://github.com/emberjs/rfcs/blob/master/text/0425-website-redesign.md) - Tracking for Website Redesign

Champion: @wifelette & @melsumner 

#### [ember-website](https://github.com/ember-learn/ember-website)
- [x] update content
- [x] extract design system from inspiration design in RFC
- [x] apply design system to [ember-styleguide](https://github.com/ember-learn/ember-styleguide)
- [x] apply ember-styleguide to main website repo
- [x] launch the main website
- [ ] apply ember-styleguide to guides
- [ ] apply ember-styleguide to cli-guides
- [ ] apply ember-styleguide to blog
- [ ] apply ember-styleguide to deprecation app
- [ ] apply ember-styleguide to ember-help-wanted

Goal: Release by 3.14

To help with this project, send a DM to `@Melanie#1618` in the [Ember Discord chat](https://discord.gg/emberjs).

**Comment by PoslinskiNet** [comment]
Looking for the new website ❤️

Any update on this one/ETA?
Do you need any help to push things forward?

**Comment by balinterdi** [comment]
I also think this would be very important to ship and would be willing to help.

**Comment by betocantu93** [comment]
I'm also willing to help 💯

**Comment by mansona** [comment]
Hey @PoslinskiNet @balinterdi and @betocantu93 thanks for the offers to help 🎉 can you please reach out to me in the #dev-ember-learning channel in the discord and we can have a chat about getting you on the team 👍 my username is @real_ate

**Comment by benkingcode** [comment]
Is there any news on this? It's been almost a year...

**Comment by mansona** [comment]
@dbbk yes the work is being tracked in https://github.com/ember-learn/ember-website/pull/361 and in https://github.com/ember-learn/ember-styleguide/pull/145

There has been a lot of work put into this effort but I'm glad to say that it looks like we're almost there 🎉

**Comment by Windvis** [comment]
Can we find the latest design somewhere? :smile:

**Comment by mansona** [comment]
@Windvis it looks like you found the latest design (by your comments on some of the PRs) but on the PR that I linked you can see the Netlify preview in the "checks" section 👍 does that answer your question?

**Comment by Windvis** [comment]
@mansona No, not really 😄. I meant the actual design files that are used as the reference for the implementation. The design preview in the RFC seems outdated so I assumed an updated design was used.

**Comment by MelSumner** [comment]
@Windvis We will be doing a write up after the release to let everyone know all the details we anticipate they will want to read about. Stay Tuned!
