### ISSUE TITLE
RFC #0457 - Tracking for Nested Invocations in Angle Bracket Syntax

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#37]
## [RFC #0457](https://github.com/emberjs/rfcs/blob/master/text/0457-nested-lookups.md) - Tracking for Nested Invocations in Angle Bracket Syntax 

Champion: @wycats @rwjblue

---

#### [ember.js](https://github.com/emberjs/ember.js)

- [x] Initial implementation https://github.com/emberjs/ember.js/pull/17719
- [x] Enable by default https://github.com/emberjs/ember.js/pull/17745
- [x] ember-angle-bracket-invocation-polyfill https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/pull/59

#### [ember-cli](https://github.com/ember-cli/ember-cli)

N/A

#### [ember-data](https://github.com/emberjs/data)

N/A

### Learning Team:

- [ ] [guides-source](https://github.com/ember-learn/guides-source)
- [ ] API docs

### Steering Committee:

N/A

**Comment by rwjblue** [comment]
Currently enabled and slated for release in 3.10

**Comment by kategengler** [comment]
Released in 3.10

**Comment by locks** [comment]
Work completed!
