### ISSUE TITLE
RFC #0410 - Tracking for Tracked Properties

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#4]
## [RFC #0410](https://github.com/emberjs/rfcs/pull/0410) - Tracking for Tracked Properties

Champion: @tomdale 

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Ember.js Team:

- [ ] Land performance fixes for tracked properties/computeds:
  - [ ] Glimmer PR: https://github.com/glimmerjs/glimmer-vm/pull/963
  - [ ] Ember PR: https://github.com/emberjs/ember.js/pull/18223
- [ ] Ensure that helpers and modifiers are fully autotracked (including class based helpers)
- [ ] Trigger sync observers asynchronously if there hasn't been a flush
- [ ] Setup async observer feature flag

### Ember CLI Team:

N/A

### Learning Team:

- [ ] Check that tracked properties work in Ember Inspector https://github.com/emberjs/ember-inspector/issues/931
- [x] Write a conversion guide for computed --> tracked  https://github.com/ember-learn/guides-source/pull/455
- [x] Write Guides sections teaching tracked, replacing computed https://github.com/ember-learn/guides-source/pull/455
- [ ] Show tracked in Ember API docs examples
- [ ] Write API docs for tracked itself
- [ ] Convert Super Rentals app to use tracked - WIP https://github.com/ember-learn/super-rentals/issues/118 and https://github.com/ember-learn/super-rentals/pull/123
- [ ] Write the prose for Super Rentals 
- [ ] Write content for the release blog post 
- [ ] Write an entry in the "Reference" section of the Guides explaining interop between Observers and tracked??? (Is this a problem?)

### Steering Committee:

N/A

**Comment by rwjblue** [comment]
@pzuraq - Now that `@tracked` is enabled on canary, would you mind updating this tracking issue to reflect what is done and what is left?

**Comment by pzuraq** [comment]
Updated! Not much left 😄

**Comment by locks** [comment]
I believe the work here has been completed!
