### ISSUE TITLE
RFC #0440 - Tracking for Decorator Support

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#41]
## [RFC #0440](https://github.com/emberjs/rfcs/blob/master/text/0440-decorator-support.md) - Tracking for Decorator Support

Champion: @pzuraq 

---

#### [ember.js](https://github.com/emberjs/ember.js)

- [x] Implement initially https://github.com/emberjs/ember.js/pull/17548
- [x] Bug fixes https://github.com/emberjs/ember.js/pull/17690
- [x] Enable feature by default https://github.com/emberjs/ember.js/pull/17828

#### [ember-cli](https://github.com/ember-cli/ember-cli)

- [x] Implement support in ember-cli-babel by default https://github.com/babel/ember-cli-babel/pull/274

#### [ember-data](https://github.com/emberjs/data)

N/A

#### [guides-source](https://github.com/ember-learn/guides-source)

- [ ] action, tracked, class in guides and API docs

N/A

### Steering Committee:

N/A

**Comment by rwjblue** [comment]
Currently enabled and slated for 3.10 release

**Comment by kategengler** [comment]
Released in Ember 3.10
