### ISSUE TITLE
RFC #0389 - Tracking for Dynamic tag names in glimmer templates

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#42]
## [RFC #0389](https://github.com/emberjs/rfcs/blob/master/text/0389-dynamic-tag-names.md) - Tracking for Dynamic tag names in glimmer templates 

Champion: @chancancode 

---

#### [glimmer-vm](https://github.com/glimmerjs/glimmer-vm)

- [ ] Implement native `element` helper

#### [ember.js](https://github.com/emberjs/ember.js)

- [ ] Implement `element` helper in "userland", using technique similar to existing polypill
- [ ] Switch to native implementation when it lands in glimmer-vm
- [ ] API docs

### Learning Team:

- [ ] Mention it in the Guides Components > Customizing a Component's Element in [guides-source](https://github.com/ember-learn/guides-source) along with strong recommendations around handling accessibility correctly
- [ ] add a note about this feature in the Accessibility topic in the [Guides](https://github.com/ember-learn/guides-source), as a thing that people should check for in their apps to make sure it's done right
- [ ] Write API docs entry that includes accessibility concerns
- [ ] Write a release blog post section which describes the features and notes about accessibility

**Comment by Panman82** [comment]
FWIW, moving an addon to Octane methodologies and Glimmer Components but cannot support a dynamic tag name just yet (`tagName` in Ember Components) because this isn't implemented and I don't want to force another dependency by using [ember-element-helper](https://github.com/tildeio/ember-element-helper).

**Comment by lolmaus** [comment]
Is this tracking up to date?
