### ISSUE TITLE
RFC #0460 - Tracking for Yieldable Named Blocks

### ISSUE THREAD

**Issue by rwjblue** [emberjs/rfc-tracking#44]
## [RFC #0460](https://emberjs.github.io/rfcs/0460-yieldable-named-blocks.html) - Tracking for Yieldable Named Blocks

Champion: @wycats @rwjblue

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

#### [ember.js](https://github.com/emberjs/ember.js)

- [ ] Upgrade the various glimmer-vm projects in Ember to latest.
- [ ] Flesh out API documentation (determine correct/best location) and coordinate with learning team

#### [ember-cli](https://github.com/ember-cli/ember-cli)

N/A

#### [ember-data](https://github.com/emberjs/data)

N/A

#### [guides-source](https://github.com/ember-learn/guides-source)

- [ ] Add segment to guides-source explaining passing and using named blocks

### Steering Committee:

N/A

**Comment by rwjblue** [comment]
A very rough idea of the work needed for upgrading in Ember can be seen in the upgrades done to Glimmer.js for the same range:

* https://github.com/glimmerjs/glimmer.js/pull/170
* https://github.com/glimmerjs/glimmer.js/pull/185
* https://github.com/glimmerjs/glimmer.js/pull/198
* https://github.com/glimmerjs/glimmer.js/pull/212

**Comment by Exelord** [comment]
Is there any rough estimation when we can expect this feature? <=3.14 or later? :)

I'm working on new addon which will use it as core functionality and I'm wondering when I could be able to release it.

**Comment by knownasilya** [comment]
Has anyone started on this, thinking of starting this week if no one has yet.

**Comment by rwjblue** [comment]
Not that I know of. I think that many/most folks with time to work on OSS at the moment are pretty focused on making Octane successful. Not an excuse or anything, just mentioning that as a reason why this is simmering for a bit...

**Comment by knownasilya** [comment]
step 1: https://github.com/emberjs/ember.js/pull/18454

**Comment by locks** [comment]
There has been progress recently and we are looking to start documenting.
These are roughly the documentation goals:

- [API docs] Adjust documentation of [`Ember.Templates.helpers` `yeld`](https://api.emberjs.com/ember/3.17/classes/Ember.Templates.helpers/methods/yield?anchor=yield) for additional named block behavior
- [API docs] Reference `yield` documentation in the [`Component` class-level documentation](https://api.emberjs.com/ember/3.17/classes/Component).
- [Blog] Write a blog that explains the feature and when a developer might want to use it and how.
- [Guides] Augment the [Block Content](https://guides.emberjs.com/release/components/block-content/) section with references to named blocks
- [Guides] Augment [Patterns for Components](https://guides.emberjs.com/release/in-depth-topics/patterns-for-components/) with prose on named blocks?

**Comment by sandstrom** [comment]
Just wanted to say that the named blocks design is awesome! 🥇
