### ISSUE TITLE
RFC #0478 - Tracking for Tracked Properties Updates

### ISSUE THREAD

**Issue by rwjblue** [emberjs/rfc-tracking#45]
## [RFC #0478](https://github.com/emberjs/rfcs/blob/master/text/0478-tracked-properties-updates.md) - Tracking for Tracked Properties Updates

Champion: @pzuraq

---

### Learning Team:

- [ ] Add/Review [`dependentKeyCompat`](https://github.com/emberjs/rfcs/blob/master/text/0478-tracked-properties-updates.md#dependentkeycompat-api-docs) in API Docs
- [ ] Add/Review Guides text on [using computed properties](https://github.com/emberjs/rfcs/blob/master/text/0478-tracked-properties-updates.md#computed-properties) - Should not be the default recommendation, but still supported.
- [ ] Add/Review Guides discussion of [when to use get/set](https://github.com/emberjs/rfcs/blob/master/text/0478-tracked-properties-updates.md#when-to-use-get-and-set-1)

### Steering Committee:

N/A
