### ISSUE TITLE
RFC #0481 - Tracking for Component Templates Co-location

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#48]
## [RFC #0481](https://github.com/emberjs/rfcs/blob/master/text/0481-component-templates-co-location.md) - Tracking for Component Templates Co-location

Champion: @chancancode, @rwjblue 	

---

#### [ember.js](https://github.com/emberjs/ember.js)

- [x] Refactor template factories to align with the RFC (https://github.com/emberjs/ember.js/pull/18096)
- [x] Implement basic runtime support (https://github.com/emberjs/ember.js/pull/18158)
  - [x] `getComponentTemplate` / `setComponentTemplate`
  - [x] Update rendering engine to use `getComponentTemplate` before attempting to resolve
- [x] Implement `templateOnlyComponent()` (https://github.com/emberjs/ember.js/pull/18190)
- [x] Implement component blueprint changes (https://github.com/emberjs/ember.js/pull/18203)
- [x] Enable feature flag (https://github.com/emberjs/ember.js/pull/18198)

#### [ember-cli](https://github.com/ember-cli/ember-cli)

- [x] Refactor template build pipeline to allow ember-cli-htmlbars changes (https://github.com/ember-cli/ember-cli/pull/8633)
- [x] Update ember-cli-htmlbars to emit the correct output for co-located components (https://github.com/ember-cli/ember-cli-htmlbars/pull/249)
  - [x] Investigate and address performance concerns

### Ember Data Team:

N/A

### Learning Team:

- [x] check to make sure Inspector works
- [x] write a blurb for the release blog
- [x] document in `octane` guides  [guides-source](https://github.com/ember-learn/guides-source) - especially requires work in the quickstart and tutorial
- [x] update [ember-cli's explanation](https://github.com/ember-learn/cli-guides) of file layouts (can be done before octane) [cli-guides](https://cli.emberjs.com/release/advanced-use/project-layouts/)
- [x] check for anywhere to update in API docs (search for places where we mention filepaths and fix them, likely revise the Components explanations).

### Steering Committee:

N/A

**Comment by rwjblue** [comment]
Initial support in Ember landed in https://github.com/emberjs/ember.js/pull/18158.

**Comment by rwjblue** [comment]
Submitted https://github.com/emberjs/ember.js/pull/18190 to add templateOnlyComponent APIs.

**Comment by GavinJoyce** [comment]
FYI, I've created an MVP codemod:

https://github.com/GavinJoyce/ember-component-template-colocation-migrator

**Comment by mehulkar** [comment]
What needs to happen to be able to have colocated glimmer components in addons?

**Comment by josemarluedke** [comment]
@mehulkar I believe that’s already working. 

See https://github.com/josemarluedke/frontile

**Comment by btecu** [comment]
@mehulkar I can also confirm is working.
