### ISSUE TITLE
RFC #0491 - Tracking for Deprecate disconnectOutlet 

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#49]
## [RFC #0491](https://github.com/emberjs/rfcs/blob/master/text/0491-deprecate-disconnect-outlet.md) - Tracking for Deprecate disconnectOutlet 

Champion: @chadhietala 

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

#### [ember.js](https://github.com/emberjs/ember.js)

- [ ] PR link: https://github.com/emberjs/ember.js/pull/19187

### Learning Team:

- [ ] Make sure Ember Inspector still works
- [ ] Write a section for the [Release Blog Post](https://github.com/ember-learn/ember-blog)
- [ ] Write an entry in the [deprecation-app](https://github.com/ember-learn/deprecation-app) and link to it from the deprecation warning
- [ ] Mark the API as deprecated in the API docs block

`disconnectOutlet` is not mentioned in the Guides nor as an example in the API docs for any other methods.

### Steering Committee:

N/A

**Comment by MelSumner** [comment]
https://github.com/emberjs/ember.js/pull/19187
