### ISSUE TITLE
RFC #0421 - Tracking for Deprecate Application Controller Router Properties

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#5]
## [RFC #0421](https://github.com/emberjs/rfcs/pull/0421) - Tracking for Deprecate Application Controller Router Properties

Champion: @chadhietala 

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Ember.js Team:
- [x] implement deprecations - https://github.com/emberjs/ember.js/pull/17573

### Ember CLI Team:

N/A

### Ember Data Team:

N/A

### Learning Team:
- [x] write deprecation guide https://github.com/ember-learn/deprecation-app/pull/276
- [x] Include in 3.10 release blog post

### Steering Committee:

N/A

**Comment by chadhietala** [comment]
Pending PR: https://github.com/emberjs/ember.js/pull/17573

**Comment by rwjblue** [comment]
FYI - This is slated for release in 3.10.

**Comment by kennethlarsen** [comment]
Deprecation is now mentioned in 3.10 blog post.

**Comment by kategengler** [comment]
Released in 3.10
