### ISSUE TITLE
RFC #0461 - Tracking for [DATA] Singleton RecordData

### ISSUE THREAD

**Issue by runspired** [emberjs/rfc-tracking#51]
## [RFC #0461](https://github.com/emberjs/rfcs/blob/master/text/0461-ember-data-singleton-record-data.md) - Tracking for [DATA] Singleton RecordData

Champion: @runspired 

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Learning Team:

- [ ] Make sure Ember Inspector still works
- [ ] Write a section for the [Release Blog Post](https://github.com/ember-learn/ember-blog)
- [ ] Write an entry in the API docs for Ember Data, including publishing TypeScript interfaces

### Steering Committee:

N/A
