### ISSUE TITLE
RFC #0466 - Tracking for Ember Data Request State Service

### ISSUE THREAD

**Issue by igorT** [emberjs/rfc-tracking#52]
## [RFC #0466](https://github.com/emberjs/rfcs/blob/master/text/0466-request-state-service.md) - Tracking for Ember Data Request State Service

Champion: @igorT 

### Learning Team:

- [ ] Make sure Ember Inspector still works
- [ ] Write a section for the [Release Blog Post](https://github.com/ember-learn/ember-blog)
- [ ] Optional - when there's a guide for Ember Data addon authors, add this to it (as mentioned in RFC)
- [ ] Write an entry in the API docs for Ember Data

### Steering Committee:

N/A

**Comment by runspired** [comment]
This is finally activated in 3.28 beta. We still need documentation though so this should be left open.
