### ISSUE TITLE
RFC #0487 - Tracking for Ember Data Custom Model Classes

### ISSUE THREAD

**Issue by igorT** [emberjs/rfc-tracking#53]
## [RFC #0487](https://github.com/emberjs/rfcs/blob/master/text/0487-custom-model-classes.md) - Tracking for Ember Data Custom Model Classes
Champion: @igorT

---

### Learning Team:

- [ ] Make sure Ember Inspector still works
- [ ] Write a section for the [Release Blog Post](https://github.com/ember-learn/ember-blog)
- [ ] Optional - if there's a guide for Ember Data addon authors, add this to it (as mentioned in RFC)
- [ ] Write an entry in the API docs for Ember Data

No action needed for the Guides.

### Steering Committee:

N/A

**Comment by jelhan** [comment]
Isn't this already implemented by https://github.com/emberjs/data/pull/6313?

**Comment by runspired** [comment]
Yes. And it is finally activated in 3.28 beta. We still need documentation though so this should be left open.
