### ISSUE TITLE
RFC #0486 - Tracking for Deprecate mouseEnter/Leave/Move Ember events

### ISSUE THREAD

**Issue by pzuraq** [emberjs/rfc-tracking#54]
## [RFC #0486](https://github.com/emberjs/rfcs/blob/master/text/0486-deprecate-mouseenter.md) - Tracking for Deprecate mouseEnter/Leave/Move Ember events

Champion: @rwjblue 

---

#### [ember.js](https://github.com/emberjs/ember.js)

- [x] Land deprecation (https://github.com/emberjs/ember.js/pull/18214)
- [x] Land deprecation guide (https://github.com/ember-learn/deprecation-app/pull/397)

### Ember CLI Team:

N/A

### Ember Data Team:

N/A

#### [guides-source](https://github.com/ember-learn/guides-source)

- [x] Remove mouseEnter, mouseLeave, and mouseMove from [Handling Events Guide](https://guides.emberjs.com/release/components/handling-events/#toc_event-names) (https://github.com/ember-learn/guides-source/pull/947)
- [x] Remove mouseEnter, mouseLeave, and mouseMove from [Component API Doc](https://api.emberjs.com/ember/release/classes/Component) (https://github.com/emberjs/ember.js/pull/18214)

### Steering Committee:

N/A

**Comment by simonihmig** [comment]
And here are the PRs for this: (I already had some prepared! :wink:)
* https://github.com/emberjs/ember.js/pull/18214
* https://github.com/ember-learn/guides-source/pull/947
* https://github.com/ember-learn/deprecation-app/pull/397

**Comment by simonihmig** [comment]
As this has shipped, can we close this?

**Comment by rwjblue** [comment]
Thank you @simonihmig!
