### ISSUE TITLE
RFC #523 - Tracking for @model named argument to route templates

### ISSUE THREAD

**Issue by locks** [emberjs/rfc-tracking#56]
## [RFC #0523](https://emberjs.github.io/rfcs/0523-model-argument-for-route-templates.html) - Tracking for @model named argument to route templates

Champion: @chancancode 

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

#### [ember.js](https://github.com/emberjs/ember.js)

- [x] Implement `@model` ([PR](https://github.com/emberjs/ember.js/pull/18345))

#### [guides-source](https://github.com/ember-learn/guides-source)

- [x] References to `this.model` need to be updated
- [x] `@model` might need to be explained before component arguments?
- [x] update tutorial material
- [x] update source code for Learning-managed Ember application
- [ ] make sure it doesn't break inspector
- [x] include in release post

### Steering Committee:

N/A

**Comment by locks** [comment]
I am marking "update source code for Learning-managed Ember application" as done despite it being worded a bit fuzzily as to exactly which applications this refers to, because we have certain hard blockers on certains applications that are being addressed and wouldn't make sense to track in the context of this RFC.

**Comment by locks** [comment]
Confirming the Ember Inspector item with the team. (cc @rwwagner90 ?)

**Comment by chancancode** [comment]
Yep this works

**Comment by locks** [comment]
Thank you!
