### ISSUE TITLE
RFC #0432 - Tracking for Contextual Helpers and Modifiers

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#6]
## [RFC #0432](https://github.com/emberjs/rfcs/pull/0432) - Tracking for Contextual Helpers and Modifiers

Champion: @chancancode 	

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Ember.js Team:

- glimmer-vm
   - [x] land new parser (@wycats)
   - [ ] implement "value everywhere" semantics in the parser
   - [ ] implement "value everywhere" semantics in the opcode compiler
- ember.js
   - [ ] implement `helper` helper
   - [ ] implement `modifier` helper

### Ember CLI Team:

N/A

### Learning Team:

- API documentation
  - [ ] `helper` helper
  - [ ]  `modifier` helper
- Guides
  - [ ] document composition patterns using both helpers
- [ ] Write the release blog post section

### Steering Committee:

N/A

**Comment by rwjblue** [comment]
I don't think this is part of Octane any longer (since we bumped MU), removing label.

**Comment by knownasilya** [comment]
What's the status on this?

**Comment by wycats** [comment]
The first task (land new parser) is [complete](https://github.com/glimmerjs/glimmer-vm/pull/1160#issuecomment-695013182) (ht: @pzuraq). The new `@handlebars/parser` needs to add support for `{{(helper)}}` to support https://github.com/emberjs/rfcs/pull/432 in strict mode, but it doesn't block landing this feature in current Ember.

The second task (implement "value everywhere semantics in the parser") has a [pull request](https://github.com/glimmerjs/glimmer-vm/pull/1168) that is waiting for a review by @puzraq. Once that is done and any changes are made to the PR, I need to write up a commit message (it's a large pull request).

@pzuraq has already begun work on implementing "value everywhere semantics" in the opcode compiler.

Once "value everywhere" semantics are implemented, implementing a `(helper)` keyword and a `(modifier)` keyword should be relatively straight-forward.

Interestingly, this work is a (large) subset of the strict mode work, which is also under heavy development.
