### ISSUE TITLE
RFC #0408 - Tracking for Decorators

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#7]
## [RFC #0408](https://github.com/emberjs/rfcs/pull/0408) - Tracking for Decorators

Champion: @tomdale

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

#### [emberjs/ember.js](https://github.com/emberjs/ember.js)

Status: Currently slated for release in Ember 3.10.0, canary flag enabled!

- Feature Work
  - [x] Initial Implementation (https://github.com/emberjs/ember.js/pull/17548)
  - [x] Updates to implementation to stage 1 (https://github.com/emberjs/ember.js/pull/17690)
  - [x] Enable Canary Flag for 3.10.0 and add/update API docs (https://github.com/emberjs/ember.js/pull/17828)
  - [x] Make `@action` work in classic classes (https://github.com/emberjs/ember.js/pull/17827)
- Bugfixes
  - [x] Expose `_getter` for ember-macro-helpers (https://github.com/emberjs/ember.js/pull/17855)
  - [x] Add assertions to computed macros to prevent improper usage (https://github.com/emberjs/ember.js/pull/17860)
  - [x] Ensure `@controller` works correctly (https://github.com/emberjs/ember.js/pull/17868)
  - [x] Revert the external name of `setClassicDecorator` (https://github.com/emberjs/ember.js/pull/17833)

### Ember CLI Team:

- [x] Provide default support in ember-cli-babel to transpile Stage 1 decorators https://github.com/babel/ember-cli-babel/pull/274

### Learning Team:
- [ ] Finish out/review decorator content in octane guides branch
- [ ] Review API Doc examples to ensure decorators are represented
- [ ] Make sure decorators work ok in the API docs app
- [ ] Make sure decorators don't break inspector
- [ ] Write a release blog post blurb
- [ ] show `@action` decorator in the Super Rentals demo app and tutorial
