### ISSUE TITLE
RFC #0415 - Tracking for Render Element Modifiers

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#8]
## [RFC #0415](https://github.com/emberjs/rfcs/pull/0415) - Tracking for Render Element Modifiers

Champions: @rwjblue, @tomdale 	

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Ember.js Team:

- [x] Implementation of addon: https://github.com/emberjs/ember-render-modifiers

### Ember CLI Team:

N/A

### Ember Data Team:

N/A

### Learning Team: 

- [ ] Review API docs in the addon: https://github.com/emberjs/ember-render-modifiers
- [ ] Update guides to reference/use the addon, likely in octane edition only

### Steering Committee:

N/A
