### ISSUE TITLE
RFC #0435 - Tracking for Forwarding Element Modifiers with "Splattributes"

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#9]
## [RFC #0435](https://github.com/emberjs/rfcs/pull/0435) - Tracking for Forwarding Element Modifiers with "Splattributes"

Champions: @rwjblue, @chancancode 	

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Ember.js Team:

- [x] Add support https://github.com/emberjs/ember.js/pull/17842
- [x] Enable feature https://github.com/emberjs/ember.js/pull/17901
- [ ] [BUGFIX beta] allow `{{action}}` modifier + component handlers, https://github.com/emberjs/ember.js/issues/17877
- [ ] Original tracking, https://github.com/emberjs/ember.js/issues/17493

### Ember CLI Team:

N/A

### Ember Data Team:

N/A

### Learning Team:

- [ ] review Guides for mentions of the behaviour of `...attributes`
- [ ] document feature in component chapter

### Steering Committee:

N/A

**Comment by cibernox** [comment]
Update: 
The feature has been merged into glimmer master (https://github.com/glimmerjs/glimmer-vm/pull/923) and backported into 0.38 in https://github.com/glimmerjs/glimmer-vm/pull/925)

**Comment by rwjblue** [comment]
Updated description a bit, this feature is enabled by default and will be included in ember-source@3.11 barring any issues...
